---
title: Converting the Hermann dataset to the new format
author: Aaron Lun
---

```{r style, echo=FALSE, results='hide', message=FALSE}
library(BiocStyle)
knitr::opts_chunk$set(error=FALSE, message=FALSE, warning=FALSE)
```

# Obtaining data from ExperimentHub

This dataset was originally generated by Charlotte Soneson.
We won't bother realigning the whole thing; instead, we'll just pull down components from ExperimentHub to create the `SingleCellExperiment`:

```{r}
library(ExperimentHub)
ehub <- ExperimentHub()

library(SingleCellExperiment)
sce <- SingleCellExperiment(
    list(spliced=ehub[["EH3469"]], unspliced=ehub[["EH3470"]]),
    colData=ehub[["EH3471"]]
)
```

We'll also do some polishing:

```{r}
library(scRNAseq)
sce <- polishDataset(sce)
sce
```

# Saving the `SingleCellExperiment`

And then we just save it again:

```{r}
meta <- list(
     title="[reprocessed, subset] The Mammalian Spermatogenesis Single-Cell Transcriptome, from Spermatogonial Stem Cells to Spermatids",
    description="Spermatogenesis is a complex and dynamic cellular differentiation process critical to male reproduction and sustained by spermatogonial stem cells (SSCs). Although patterns of gene expression have been described for aggregates of certain spermato- genic cell types, the full continuum of gene expression patterns underlying ongoing spermatogenesis in steady state was previously unclear. Here, we catalog single-cell transcriptomes for >62,000 individual spermatogenic cells from immature (postnatal day 6) and adult male mice and adult men. This allowed us to resolve SSC and progenitor spermatogonia, elucidate the full range of gene expression changes during male meiosis and spermiogenesis, and derive unique gene expression signatures for multiple mouse and human spermatogenic cell types and/or subtypes. These transcriptome datasets provide an information-rich resource for studies of SSCs, male meiosis, testicular cancer, male infertility, or contraceptive development, as well as a gene expression roadmap to be emulated in efforts to achieve spermatogenesis in vitro.

This dataset contains only the cells for a single sample (adult mouse 3), reprocessed from FASTQ files with the `alevin` and `tximeta` packages to obtain spliced and unspliced counts. These count matrices are stored in separate assays of the `SingleCellExperiment`. This object is intended as a test dataset for splicing-related steps like RNA velocity calculations.",
    taxonomy_id="10090",
    genome="GRCm38",
    sources=list(
        list(provider="GEO", id="GSE109033"),
        list(provider="GEO", id="GSM2928341"),
        list(provider="SRA", id="SRR6459157"),
        list(provider="PubMed", id="30404016"),
        list(provider="ExperimentHub", id="EH3469"),
        list(provider="ExperimentHub", id="EH3470"),
        list(provider="ExperimentHub", id="EH3471")
    ),
    maintainer_name="Charlotte Soneson",
    maintainer_email="charlottesoneson@gmail.com"
)

saveDataset(sce, "2023-12-20", meta)
```

# Session information {-}

```{r}
sessionInfo()
```
