write.csv(file="../../extdata/2.4.0/metadata-mair-pbmc.csv", 
    data.frame(
        Title = sprintf("Mair PBMCs %s", c("RNA counts", "RNA rowData",
                                           "ADT counts", "ADT rowData", "colData")),
        Description = sprintf("%s for the Mair healthy PBMCs targeted CITEseq dataset", 
            c("RNA count matrix", "RNA rowdata","ADT count matrix","ADT rowdata",
              "Per-cell metadata")),
        RDataPath = file.path("scRNAseq", "mair-pbmc", "2.4.0",
                              c("rna_counts.rds", "rna_rowdata.rds", "adt_counts.rds",
                                "adt_rowdata.rds","coldata.rds")),
        BiocVersion="3.11",
        Genome="hg38",
        SourceType=c("CSV","ZIP"),
        SourceUrl="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE135325",
        SourceVersion="May 19, 2020",
        Species="Homo sapiens",
        TaxonomyId="9606",
        Coordinate_1_based=NA,
        DataProvider="GEO",
        Maintainer="Stephany Orjuela <sorjuelal@gmail.com>",
        RDataClass=c("dgCMatrix", "DFrame"),
        DispatchClass="Rds",
        stringsAsFactors = FALSE
    ),
    row.names=FALSE
)
