write.csv(file="../extdata/2.4.0/metadata-hermann-spermatogenesis.csv", 
          data.frame(
              Title = sprintf("Hermann Spermatogenesis %s", c("spliced counts", "unspliced counts", "colData")),
              Description = sprintf("%s for the Hermann spermatogenesis single-cell RNA-seq dataset", 
                                    c("Spliced count matrix", "Unspliced count matrix", "Per-cell metadata")),
              RDataPath = file.path("scRNAseq", "hermann-spermatogenesis", "2.4.0", 
                                    c("spliced.rds", "unspliced.rds", "coldata.rds")),
              BiocVersion="3.12",
              Genome="GRCm38",
              SourceType="FASTQ",
              SourceUrl="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2928341",
              SourceVersion="",
              Species="Mus musculus",
              TaxonomyId="10090",
              Coordinate_1_based=NA,
              DataProvider="GEO",
              Maintainer="Charlotte Soneson <charlottesoneson@gmail.com>",
              RDataClass=c("dgCMatrix", "dgCMatrix", "DFrame"),
              DispatchClass="Rds",
              stringsAsFactors = FALSE
          ),
          row.names=FALSE)
