write.csv(file="../../extdata/2.4.0/metadata-stoeckius-hashing.csv", 
    data.frame(
        Title = sprintf("Stoeckius %s counts", 
            c("PBMC RNA", "mouse RNA", "HTO", "PBMC ADT-1", "PBMC ADT-2", "cell line RNA", "cell line HTO")),
        Description = sprintf("%s count matrix for %s in the Stoeckius single-cell RNA-seq dataset", 
            c("RNA", "RNA", "HTO", "First ADT", "Second ADT", "RNA", "HTO"),
            c("hashed PBMCs", "unlabelled mouse controls", "hashed PBMCs", "hashed PBMCs", "hashed PBMCs", 
                "hashed cell lines", "hashed cell lines")),
        RDataPath = file.path("scRNAseq", "stoeckius", "2.4.0", 
            c("pbmc_human_counts.rds", "pbmc_mouse_counts.rds",
                "pbmc_hto_counts.rds", "pbmc_adt1_counts.rds", "pbmc_adt2_counts.rds",
                "cell_rna_counts.rds", "cell_hto_counts.rds")),
        BiocVersion="3.12",
        Genome=c("hg19", "mm10", "hg19", "hg19", "hg19", "hg19", "hg19"),
        SourceType=c("TSV", "TSV", "CSV", "CSV", "CSV", "TSV", "CSV"),
        SourceUrl="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE108313",
        SourceVersion=c(
            "GSM2895282_Hashtag-RNA.umi.txt.gz",
            "GSM2895282_Hashtag-RNA.umi.txt.gz",
            "GSM2895283_Hashtag-HTO-count.csv.gz",
            "GSM2895284_Hashtag-ADT1-count.csv.gz",
            "GSM2895284_Hashtag-ADT2-count.csv.gz",
            "GSM3501446_MixCellLines-RNA.umi.txt.gz",
            "GSM3501447_MixCellLines-HTO-counts.csv.gz"
        ),
        Species=c("Homo sapiens", "Mus musculus", "Homo sapiens", "Homo sapiens", "Homo sapiens", "Homo sapiens", "Homo sapiens"),
        TaxonomyId=c("9606", "10090", "9606", "9606", "9606", "9606", "9606"),
        Coordinate_1_based=NA,
        DataProvider="GEO",
        Maintainer="Aaron Lun <infinite.monkeys.with.keyboards@gmail.com>",
        RDataClass=c("dgCMatrix", "dgCMatrix", "matrix", "matrix", "matrix", "dgCMatrix", "matrix"),
        DispatchClass="Rds",
        stringsAsFactors = FALSE
    ),
    row.names=FALSE)
