write.csv(file="../../extdata/2.4.0/metadata-kotliarov-pbmc.csv", 
          data.frame(
              Title = sprintf("Kotliarov PBMCs %s", c("RNA counts", "RNA rowData",
                                               "ADT counts", "ADT rowData", "colData")),
              Description = sprintf("%s for the Kotliarov influenza-vaccinated healthy PBMCs CITEseq dataset", 
                                  c("RNA count matrix", "RNA rowdata","ADT count matrix","ADT rowdata",
                                    "Per-cell metadata")),
              RDataPath = file.path("scRNAseq", "kotliarov-pbmc", "2.4.0",
                                  c("rna_counts.rds", "rna_rowdata.rds", "adt_counts.rds",
                                    "adt_rowdata.rds","coldata.rds")),
              BiocVersion="3.11",
              Genome="hg19",
              SourceType=c("RDS"),
              SourceUrl="https://nih.figshare.com/ndownloader/files/20706642",
              SourceVersion="H1_day0_demultilexed_singlets.RDS",
              Species="Homo sapiens",
              TaxonomyId="9606",
              Coordinate_1_based=NA,
              DataProvider="figshare",
              Maintainer="Stephany Orjuela <sorjuelal@gmail.com>",
              RDataClass=c("dgCMatrix", "DFrame"),
              DispatchClass="Rds",
              stringsAsFactors = FALSE
          ),
          row.names=FALSE
)