---
title: Downloading ERCC spike-in concentrations
author: Alan O'Callaghan
date: 18 May 2019
output:
  BiocStyle::html_document:
    titlecaps: false
    toc_float: true
bibliography: ref.bib
---

```{r style, echo=FALSE, results='hide', message=FALSE}
library(BiocStyle)
knitr::opts_chunk$set(error=FALSE, message=FALSE, warning=FALSE)
```

# Downloading the data

The data can be sourced from Thermo's website.

```{r}
library(BiocFileCache)
bfc <- BiocFileCache("raw_data", ask = FALSE)
path <- bfcrpath(
    bfc, 
    "https://assets.thermofisher.com/TFS-Assets/LSG/manuals/cms_095046.txt"
)
```

Read in the table with "improper" column names.

```{r}
table <- read.delim(path, check.names = FALSE, stringsAsFactors = FALSE)
columns <- c(
    "ERCC ID",
    "subgroup",
    "concentration in Mix 1 (attomoles/ul)",
    "concentration in Mix 2 (attomoles/ul)",
    "expected fold-change ratio",
    "log2(Mix 1/Mix 2)"
)
table <- table[, columns]
```

We now save the table to `r Biocpkg("ExperimentHub")`.

```{r}
path <- file.path("scRNAseq", "ercc-spike-in-concentrations", "1.0.0")
dir.create(path, showWarnings = FALSE, recursive = TRUE)
saveRDS(table, file = file.path(path, "concentrations.rds"))
```

# Session information

```{r}
sessionInfo()
```

# References
