#' Upload a directory to the gypsum backend
#'
#' Upload a directory containing one or more datasets to the gypsum backend as a versioned asset.
#' This requires uploader permissions to the \pkg{scRNAseq} project.
#' 
#' @param dir String containing the path to a directory.
#' This can either be the same directory generated by \code{\link{saveDataset}}
#' or it can be a parent directory containing multiple subdirectories generated by \code{\link{saveDataset}}.
#' @param name String containing the name of the asset. 
#' This should not contain \code{/} or start with \code{..}.
#' @param version String containing the version of the asset. 
#' This should not contain \code{/} or start with \code{..}.
#' @param package String containing the package name.
#' @param probation Logical scalar indicating whether this should be a probational upload.
#' @param url String containing the URL to the gypsum REST API.
#' Defaults to \code{\link[gypsum]{restUrl}}.
#' @param token String containing a GitHub access token for authentication.
#' Defaults to \code{\link[gypsum]{accessToken}}.
#' @param concurrent Integer scalar specifying the number of concurrent uploads.
#' @param abort.failed Logical scalar indicating whether to abort the upload on any failure.
#' Setting this to \code{FALSE} can be helpful for diagnosing upload problems.
#' @param cache String containing the path to the same cache used in \code{\link{fetchDataset}}.
#' Used to create upload links when an existing dataset is saved into \code{dir}, e.g., for updates.
#'
#' @return On successful upload, \code{NULL} is invisibly returned.
#'
#' @details
#' \code{dir} may contain multiple related datasets in subdirectories, 
#' generated by \code{\link{saveDataset}} calls on different \linkS4class{SummarizedExperiment} objects.
#' This is occasionally useful for studies with multiple outputs, e.g., for different species or modalities.
#'
#' The \code{probation} flag allows contributors to test their uploads 
#' and for the \pkg{scRNAseq} maintainers to review the content before approval.
#' Note that uploads from untrusted users are automatically probational so setting \code{probation=FALSE} is not explicitly required in such cases.
#'
#' @seealso
#' \code{\link{saveDataset}}, to save data to a directory.
#'
#' \code{\link{fetchDataset}}, to download an existing dataset into the current sesssion.
#'
#' @author Aaron Lun
#' @examples
#' library(SingleCellExperiment)
#' sce <- SingleCellExperiment(list(counts=matrix(rpois(1000, lambda=1), 100, 10)))
#' rownames(sce) <- sprintf("GENE_%i", seq_len(nrow(sce)))
#' colnames(sce) <- head(LETTERS, 10)
#'
#' meta <- createMetadata(
#'     title="My dataset",
#'     description="This is my dataset",
#'     taxonomy.id="10090",
#'     genome="GRCh38",
#'     sources=list(list(provider="GEO", id="GSE12345")),
#'     maintainer.name="Shizuka Mogami",
#'     maintainer.email="mogami.shizuka@765pro.com"
#' )
#' 
#' cache <- tempfile()
#' saveDataset(sce, cache, meta)
#'
#' version <- as.character(Sys.Date())
#' if (interactive()) {
#'     # Uploading a probational version for test purposes.
#'     uploadDirectory(cache, "test", version, probation=TRUE)
#'
#'     # Cleaning up after ourselves.
#'     gypsum::rejectProbation("scRNAseq", "test", version)
#' }
#'
#' @export
uploadDirectory <- function(dir, name, version, package="scRNAseq", cache=NULL, probation=FALSE, url=NULL, token=NULL, concurrent=1, abort.failed=TRUE) {
    if (is.null(url)) {
        url <- gypsum::restUrl()
    }
    if (is.null(token)) {
        token <- gypsum::accessToken()
    }

    listing <- list_files(dir, cache=cache)

    blob <- gypsum::startUpload(
        project=package,
        asset=name,
        version=version, 
        files=listing$files,
        links=listing$links,
        directory=dir,
        probation=probation,
        url=url,
        token=token
    )

    success <- FALSE
    if (abort.failed) {
        on.exit({
            if (!success) {
                gypsum::abortUpload(blob)
            }
        })
    }

    gypsum::uploadFiles(blob, directory=dir, url=url, concurrent=concurrent)
    gypsum::completeUpload(blob, url=url)

    success <- TRUE
    invisible(NULL)
}

append_path_or_null <- function(dir, base) {
    if (is.null(dir)) {
        base
    } else {
        paste0(dir, "/", base)
    }
}

list_files <- function(full, cache=NULL) {
    if (is.null(cache)) {
        cache <- gypsum::cacheDirectory()
    }
    # Going through the directory contents and converting symlinks to upload links.
    gypsum::prepareDirectoryUpload(full, links="always", cache=cache)
}
